### ISSUE TITLE
[DynamicLevies] TODO: complete experiments with huge, hidden demesne law groups

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#31]
Experiment which fulfills remaining feasibility questions (and some more) regarding current DynamicLeviesDesign plan, on the topic of direct levy law modifiers rather than character modifiers:
- [x] Create a demesne law group that has `potential = { always = no }`.  Fill it with 64 laws that have observable effects if enacted (use the new `demesnse_size` law modifier as an easy way to observe the effects and test that new feature at the same time). For each law's `effect`, call a singular _law supplement event_ on the title holder.
- [x] Write a support tool that auto-generates that law group, parameterized.  This will be extended later to calculate the modifiers for each law (and generate all the corresponding law code) according to the given behavioral parameters. As such, this is actually part of the final implementation.
- [x] Write the law supplement event to check against the FROM scope, probing to determine if it's the originating title (e.g., check whether `FROM = { title = k_england }` in the event if testing as William the Conqueror) or simply null.  This FROM-checking is a curiosity, while successfully receiving the event for a hidden law being enacted by event  is a feasibility experiment.
- [x] Write a test driver that uses `add_law` to enact one of the highest-numbered 64 laws on ROOT's primary title.  (Don't know whether engine supports so many laws in a single group. Never been done.)
- [x] Put it all to the test at once with an in-game test run of the driver.
1. Did the law's modifier take effect despite its false potential?  E.g., has your demesne cap been raised accordingly?
2. Did the law execute its `effect` clause despite false potential, as evidenced by receiving the law supplement event?  Was FROM also the originating title?

If the answer to all of these is yes (except for the curiosity about FROM in the law supplement event), then we know that the fundamental design of DynamicLevies can and will take the planned title-based, direct levy law scaling approach.  AFAIK, nothing is blocking the beginning of implementation immediately thereafter.

The only other open question at time of this writing is simply a confirmation experiment for inheritance triggering, which has workarounds if it fails and thus won't affect any of the core implementation.
